### ISSUE TITLE
Build netlify previews for proposed posts

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-community-blog#5]
Building on from #4 

It would be nice to see a preview of proposed blog posts. As I understand we would need to trigger a Netlify build preview on PRs similar to how this works in farmos/farmos.org. But I think Netlfiy does that automatically so we might need to implement this one ourselves - cc @jgaehring :-)

**Comment by jgaehring** [comment]
I've used the [farmOS/farmOS.org@source/farmOS](https://github.com/farmOS/farmOS.org/tree/source/farmOS) branch in the past as an ad hoc solution, but it could be formalized into a better workflow. See https://github.com/farmOS/farmOS/pull/505#issuecomment-1046061060 as an example.

**Comment by jgaehring** [comment]
From the Element chat over the course of this past week:

> **mstenta**  
> What's the best way to test how that displays? Do I need to run code locally? We don't have a way to preview in Netlify yet, huh?
> 
> **jgaehring**  
> I briefly mentioned this to this [here](https://github.com/farmOS/farmOS-community-blog/issues/5), but I think the best way would be to set up preview branches in the farmOS/farmOS.org repo that targets a specific branch on a source repo, maybe set up a staging repo or something for each for drafts, or what have you, like I did with the fork for that PR:
> 
> https://github.com/farmOS/farmOS.org/blob/source/farmOS/source-repos.js#L7
> 
> could probably finesse the GH action to target PR's on source repo's and build from whatever fork or branch is being merged, but that would be the gist of it
> 
> **paul121**  
> interesting. I wonder if we could kinda make our own "deploy preview" manually.... could we maybe have a GH action in farmOS-community-blog that clones farmOS/farmOS.org, changes the source repo branch to farmOS-community-blog@PR, runs webpack build, and saves it as an artifact viewable in the PR?

So yea, I'm gonna open a PR for that in a moment, and set up a `source/farmOS-community-blog` branch in the [farmOS/farmOS.org](https://github.com/farmOS/farmOS.org) for it to target, curious what y'all think.

**Comment by jgaehring** [comment]
OK, I'm gonna have to step away until next week after this, but I pushed this `netlify-preview` branch up a few moments ago, instead of opening a PR:

https://github.com/farmOS/farmOS-community-blog/tree/netlify-preview/.github/workflows/netlify-preview.yml

Initially I thought it could be a branch to test PR's against before opening a PR for the `netlify-preview` branch itself, but I just realized/remembered it will actually need to keep that branch alive and push to it instead. This is because there also needs to be a corresponding `source/farmOS-community-blog` branch in the `farmOS/farmOS.org` repo itself, which has a modified `site-data.js` file that knows to use the `netlify-preview` branch of this repo:

https://github.com/farmOS/farmOS.org/blob/05910a3cbe7464883cde122012844979d10b469a/site-data.js#L61-L73

In the future, we can either set up corresponding `source/*` branches in the farmOS/farmOS.org repo for each of the other sources (eg, farmOS.js and farmOS.py). Or we can have just one `source-preview` branch that points its `site-data.js` file at all existing sources' preview branches. That might be easier, since I don't _think_ there would need to be additional changes to that `source-preview` branch that would also be specific to just one source, but I'm not sure. It might be handy if, for instance, we made changes to the `BLOG_TEMPLATE` to display video differently than the `DOCS_TEMPLATE`, but for that kind of feedback it's probably best to do all that on a local dev server, not though GH actions. These source previews should really just be for previewing new content, imo.

**Comment by jgaehring** [comment]
Looking at some of @mstenta's commits and the _full_ deploy log on Netlify, it looks like the original push (ts @ 2:14pm EST) _did_ succeed:

https://app.netlify.com/sites/gracious-brattain-bdd606/deploys/636d4d975f609b00097813d7

I was just looking at the wrong list of deployments [when I said in the Element chat that it had not](https://matrix.to/#/!rxZezKXfxOKJxTgNGs:matrix.org/$166810783116458idDrX:matrix.org?via=libera.chat&via=matrix.org&via=oblak.be). The push of commit 1da000134e132c986079dbf107a67f10f5ca587c _failed_, but we're still seeing [the preview](https://636d4d975f609b00097813d7--gracious-brattain-bdd606.netlify.app/) because of the previous successful deployment, and because what failed was the trigger itself, so no new build replaced it:

https://app.netlify.com/sites/gracious-brattain-bdd606/deploys/636d513c2559600008c60430

So now, we have the choice of either reverting to 771c76236078d81da9e2135d521fe99e43d2a8f0, or in the farmOS/farmOS.org repo we can create a branch called `source-preview`. I'm inclined to stick w/ `source/farmOS-community-blog` for now, b/c we know it works and seems simplest, but what do others think?

**Comment by mstenta** [comment]
Oh excellent! Yea feel free to revert my commits @jgaehring! I was fumbling around a bit and figured it would need review/cleanup.

**Comment by jgaehring** [comment]
Reverted the changes and the new build hook worked:

https://source-farmos-community-blog--gracious-brattain-bdd606.netlify.app/blog/2022/farmos-in-5-minutes-video

Closing.

**Comment by paul121** [comment]
Sorry, I wasn't able to follow this convo too closely. I guess I'm a little confused.. so now we can get a preview if we merge into the `netlify-preview` branch first? That's a nice next step but it would be nice if a contributor could get a preview without any action from the "maintainers" of this repo. Ideally write a blog post entirely from the Github UI and see a preview!

The gotcha here seems to be that netlify needs a branch on `farmOS/farmOS.org` to use for any deploy preview. But for pull requests to the source repo it's challenging to get a branch that points to the PR source... but what if we could parameterize the source `remote` and `branch` in [`site-data.js`](https://github.com/farmOS/farmOS.org/blob/main/site-data.js) to populate from an env variable? I think we could provide these values from the Netlify build hook payload (currently we don't send anything): https://docs.netlify.com/configure-builds/build-hooks/#payload. We could populate that payload in an action for PRs to this community blog repo.

Separately, just came across the github action `workflow_dispatch` feature, and wonder if we could leverage that here too. It lets you configure input for a workflow that can be trigger via CLI/API or even manually via the UI: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch I think that `farmOS/farmOS.org` could host this workflow and let our other source repos dispatch this workflow via the github API in their respective workflows. The source repos would still need a github action workflow, but basically it would mean that only the `farmOS/farmOS.org` repo would need a netlify token. The workflow could itself parameterize the input required for this "deploy preview for PRs to source repos", making it easier for other source repos (farmOS/farmOS) to get previews when changing their docs as well... :smiley:

**Comment by jgaehring** [comment]
> but what if we could parameterize the source `remote` and `branch` in [`site-data.js`](https://github.com/farmOS/farmOS.org/blob/main/site-data.js) to populate from an env variable? I think we could provide these values from the Netlify build hook payload (currently we don't send anything): https://docs.netlify.com/configure-builds/build-hooks/#payload. We could populate that payload in an action for PRs to this community blog repo.

I like this idea. As I think I said before, there are better ways to finesse all of this, but it was the easiest scenario I could come up with on the fly. I don't think I have time to look at how to parameterize those values in site-data.js, probably needs to be Node environment variables, but others arewelcome to take a stab at it.
